@BASE_API=http://localhost:3000

###
GET  {{BASE_API}}
Content-Type: application/json

### POST /api/users/register
POST {{BASE_API}}/users/register
Content-Type: application/json

{
  "name":"jk",
  "email": "jk2@gmail.com",
  "username": "jk2",
  "password": "Aa112233"
}

### POST /api/auth/login
POST {{BASE_API}}/auth/login
Content-Type: application/json

{
  "username": "jk2",
  "password": "Aa112233"
}

### POST /api/auth/refresh
POST {{BASE_API}}/auth/refresh
Content-Type: application/json

{
  "userId": "2",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImlhdCI6MTc1NjMyNzY4NCwiZXhwIjoxNzU2OTMyNDg0fQ.Z6Yyp_g6VBafa48V0uFSGsUeyoW_tSlSDXYWjITnBQ8"
}

